import { useState } from "react";
import { request } from "../services/api";

function OtpVerify({ email, showNotice }) { const [otp, setOtp] = useState(""); const [busy, setBusy] = useState(false); const verify = async (event) => { event.preventDefault(); try { setBusy(true); await request("/auth/verify-otp", { method: "POST", body: { email, otp } }); showNotice("Email verified. You can sign in now."); } catch (error) { showNotice(error.message, "error"); } finally { setBusy(false); } }; return <form onSubmit={verify}><h2>Verify your email</h2><p className="muted">Enter the six-digit code sent to {email}.</p><label>Verification code<input required inputMode="numeric" maxLength="6" value={otp} onChange={(event) => setOtp(event.target.value)}/></label><button className="primary wide" disabled={busy}>{busy ? "Verifying…" : "Verify account"}</button></form>; }

export default function Auth({ onLogin, showNotice }) {
  const [mode, setMode] = useState("login"); const [form, setForm] = useState({ name: "", phone: "", email: "", password: "" }); const [busy, setBusy] = useState(false); const [pending, setPending] = useState(false);
  const submit = async (event) => { event.preventDefault(); try { setBusy(true); if (mode === "login") return onLogin(await request("/auth/login", { method: "POST", body: { email: form.email, password: form.password } })); await request("/auth/register", { method: "POST", body: form }); setPending(true); showNotice("We sent a verification code to your email."); } catch (error) { showNotice(error.message, "error"); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-aside"><p className="eyebrow">TURF COMMUNITY</p><h1>More playing.<br/><em>Less planning.</em></h1><p>Join players and venue owners building a better local sports scene.</p></section><section className="auth-card"><div className="tabs"><button className={mode === "login" ? "active" : ""} onClick={() => { setMode("login"); setPending(false); }}>Sign in</button><button className={mode === "register" ? "active" : ""} onClick={() => { setMode("register"); setPending(false); }}>Create account</button></div>{pending ? <OtpVerify email={form.email} showNotice={showNotice} /> : <form onSubmit={submit}>{mode === "register" && <><label>Full name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label>Mobile number<input required value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })}/></label></>}<label>Email address<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })}/></label><label>Password<input required minLength="6" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })}/></label><button className="primary wide" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form>}<p className="form-footnote">{mode === "login" ? "Use your verified customer or venue-owner account." : "By creating an account, you agree to use TURF responsibly."}</p></section></main>;
}
