import { useEffect, useState } from "react";
import { money, prettyDate, request } from "../services/api";

function Stat({ title, value }) { return <div className="stat"><span>{title}</span><strong>{value}</strong></div>; }

function AdminDashboard({ token, user, showNotice }) { const [income, setIncome] = useState(null); useEffect(() => { if (user.role === "playground-admin") request("/payments/playground-admin/income", { token }).then(setIncome).catch((error) => showNotice(error.message, "error")); }, []); return <main className="page dashboard"><p className="eyebrow">{user.role.replace("-", " ").toUpperCase()}</p><h1>Welcome, {user.name}.</h1><p className="muted">Your operations dashboard is connected to the same API. Manage venues, slots and tournaments through the existing admin workflows.</p>{user.role === "playground-admin" && <div className="dash-stats"><Stat title="Slot income" value={money(income?.slotTotal)}/><Stat title="Tournament income" value={money(income?.tournamentTotal)}/><Stat title="Total collected" value={money(income?.total)}/></div>}<div className="empty"><strong>Venue management is ready on the API.</strong><p>Use your venue-admin account to create slots and manage all bookings.</p></div></main>; }

export default function Dashboard({ token, user, openAuth, showNotice }) {
  const [bookings, setBookings] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!token || user?.role !== "customer") { setLoading(false); return; } request("/bookings/my-bookings", { token }).then(setBookings).catch((error) => showNotice(error.message, "error")).finally(() => setLoading(false)); }, [token, user?.role]);
  if (!user) return <main className="page login-prompt"><h1>Your game plan, all in one place.</h1><p>Sign in to see bookings, tickets, and upcoming matches.</p><button className="primary" onClick={openAuth}>Sign in to continue</button></main>;
  if (user.role !== "customer") return <AdminDashboard token={token} user={user} showNotice={showNotice}/>;
  const cancel = async (id) => { try { await request(`/bookings/${id}/cancel`, { method: "PATCH", token }); setBookings((current) => current.map((booking) => booking._id === id ? { ...booking, bookingStatus: "Cancelled" } : booking)); showNotice("Booking cancelled successfully."); } catch (error) { showNotice(error.message, "error"); } };
  return <main className="page dashboard"><p className="eyebrow">PLAYER DASHBOARD</p><h1>Hi, {user.name?.split(" ")[0]}.</h1><div className="dash-stats"><Stat title="Upcoming games" value={bookings.filter((booking) => booking.bookingStatus === "Confirmed").length}/><Stat title="Total bookings" value={bookings.length}/><Stat title="Member since" value="TURF"/></div><h2>Your bookings</h2>{loading ? <p>Loading your bookings...</p> : <div className="booking-list">{bookings.length ? bookings.map((booking) => <article className="booking-row" key={booking._id}><div><strong>{booking.playground?.name || "Playground"}</strong><p>{prettyDate(booking.bookingDate)} / {booking.startTime}-{booking.endTime}</p></div><span className={`status ${booking.bookingStatus?.toLowerCase()}`}>{booking.bookingStatus}</span>{["Pending", "Confirmed"].includes(booking.bookingStatus) && <button className="text-button danger" onClick={() => cancel(booking._id)}>Cancel</button>}</article>) : <div className="empty"><strong>No bookings yet.</strong><p>Choose a venue and reserve your first slot.</p></div>}</div>}</main>;
}
