import { useEffect, useState } from "react";
import { isoDate, money, request, toMinutes } from "../services/api";

const fallbackImage = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80";

export default function VenueDetail({ venue, token, user, openAuth, showNotice }) {
  const [date, setDate] = useState(isoDate()); const [slots, setSlots] = useState([]); const [loading, setLoading] = useState(false); const [selectedSlot, setSelectedSlot] = useState(null); const [paying, setPaying] = useState(false);
  useEffect(() => { setSelectedSlot(null); if (!venue?._id) return; setLoading(true); request(`/slots/availability?playground=${venue._id}&date=${date}`).then((data) => setSlots(data || [])).catch((error) => showNotice(error.message, "error")).finally(() => setLoading(false)); }, [venue?._id, date]);
  if (!venue) return <main className="page empty"><strong>Select a venue to get started.</strong></main>;
  const reserve = async () => { if (!user || !token) return openAuth(); if (user.role !== "customer") return showNotice("Bookings can be made from a customer account.", "error"); if (!selectedSlot) return showNotice("Choose an available slot first.", "error"); try { setPaying(true); const duration = (toMinutes(selectedSlot.endTime) - toMinutes(selectedSlot.startTime)) / 60; const booking = await request("/bookings", { method: "POST", token, body: { playground: venue._id, bookingDate: date, startTime: selectedSlot.startTime, endTime: selectedSlot.endTime, duration } }); await request("/payments", { method: "POST", token, body: { booking: booking._id, paymentMethod: "bKash" } }); showNotice("Booking confirmed and your digital ticket is ready!"); setSelectedSlot(null); } catch (error) { showNotice(error.message, "error"); } finally { setPaying(false); } };
  return <main className="venue-page"><section className="venue-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(8,20,18,.85), rgba(8,20,18,.15)), url(${venue.coverImage || fallbackImage})` }}><div><p className="eyebrow">{venue.sportType} VENUE</p><h1>{venue.name}</h1><p>⌖ {venue.address}, {venue.area}</p></div></section><section className="booking-layout"><div className="venue-info"><div className="rating">★ {(venue.averageRating || 0).toFixed(1)} <span>({venue.totalReviews || 0} reviews)</span></div><h2>Built for your best game.</h2><p>{venue.description || "A great local venue for your next match."}</p><div className="facility-list">{(venue.facilities || ["Changing room", "Parking", "Floodlights"]).map((item) => <span key={item}>✓ {item}</span>)}</div><div className="venue-contact"><span>Open {venue.openingTime} — {venue.closingTime}</span><a href={`tel:${venue.phone}`}>Call venue</a></div></div><aside className="booking-panel"><p className="eyebrow">RESERVE A SLOT</p><h2>When do you want to play?</h2><input aria-label="Booking date" type="date" min={isoDate()} value={date} onChange={(event) => setDate(event.target.value)} /><div className="slot-list">{loading ? <p className="muted">Loading slots…</p> : slots.length ? slots.map((slot) => <button disabled={!slot.available} className={`slot ${selectedSlot?._id === slot._id ? "selected" : ""}`} key={slot._id} onClick={() => setSelectedSlot(slot)}><span>{slot.startTime} — {slot.endTime}</span><strong>{slot.available ? money(slot.price || venue.pricing?.evening) : "Booked"}</strong></button>) : <p className="muted">No published slots for this date.</p>}</div><button className="primary reserve" disabled={paying || !selectedSlot} onClick={reserve}>{paying ? "Confirming…" : selectedSlot ? `Book for ${money(selectedSlot.price || venue.pricing?.evening)}` : "Select a slot"}</button><small>Demo bKash payment is used in this version.</small></aside></section></main>;
}
